package pojo;
// Generated May 21, 2016 2:00:13 PM by Hibernate Tools 4.3.1



/**
 * Appadmin generated by hbm2java
 */
public class Appadmin  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String mail;
     private String master;
     private String imageurl;
     private String password;

    public Appadmin() {
    }

	
    public Appadmin(String name, String password) {
        this.name = name;
        this.password = password;
    }
    public Appadmin(String name, String mail, String master, String imageurl, String password) {
       this.name = name;
       this.mail = mail;
       this.master = master;
       this.imageurl = imageurl;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getMaster() {
        return this.master;
    }
    
    public void setMaster(String master) {
        this.master = master;
    }
    public String getImageurl() {
        return this.imageurl;
    }
    
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


