package pojo;
// Generated May 21, 2016 2:00:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Appuser generated by hbm2java
 */
public class Appuser  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String mail;
     private String phone;
     private String birthyear;
     private String imageurl;
     private String password;
     private String latitude;
     private String longtude;
     private Set usermessages = new HashSet(0);
     private Set userborrowbooks = new HashSet(0);
     private Set userbooks = new HashSet(0);

    public Appuser() {
    }

	
    public Appuser(String name, String password, String latitude, String longtude) {
        this.name = name;
        this.password = password;
        this.latitude = latitude;
        this.longtude = longtude;
    }
    public Appuser(String name, String mail, String phone, String birthyear, String imageurl, String password, String latitude, String longtude, Set usermessages, Set userborrowbooks, Set userbooks) {
       this.name = name;
       this.mail = mail;
       this.phone = phone;
       this.birthyear = birthyear;
       this.imageurl = imageurl;
       this.password = password;
       this.latitude = latitude;
       this.longtude = longtude;
       this.usermessages = usermessages;
       this.userborrowbooks = userborrowbooks;
       this.userbooks = userbooks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getBirthyear() {
        return this.birthyear;
    }
    
    public void setBirthyear(String birthyear) {
        this.birthyear = birthyear;
    }
    public String getImageurl() {
        return this.imageurl;
    }
    
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getLongtude() {
        return this.longtude;
    }
    
    public void setLongtude(String longtude) {
        this.longtude = longtude;
    }
    public Set getUsermessages() {
        return this.usermessages;
    }
    
    public void setUsermessages(Set usermessages) {
        this.usermessages = usermessages;
    }
    public Set getUserborrowbooks() {
        return this.userborrowbooks;
    }
    
    public void setUserborrowbooks(Set userborrowbooks) {
        this.userborrowbooks = userborrowbooks;
    }
    public Set getUserbooks() {
        return this.userbooks;
    }
    
    public void setUserbooks(Set userbooks) {
        this.userbooks = userbooks;
    }




}


