package pojo;
// Generated May 21, 2016 2:00:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Books generated by hbm2java
 */
public class Books  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int yearrelase;
     private String authorname;
     private String timestimp;
     private String imageurl;
     private Set userbooks = new HashSet(0);

    public Books() {
    }

	
    public Books(String name, int yearrelase, String authorname) {
        this.name = name;
        this.yearrelase = yearrelase;
        this.authorname = authorname;
    }
    public Books(String name, int yearrelase, String authorname, String timestimp, String imageurl, Set userbooks) {
       this.name = name;
       this.yearrelase = yearrelase;
       this.authorname = authorname;
       this.timestimp = timestimp;
       this.imageurl = imageurl;
       this.userbooks = userbooks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getYearrelase() {
        return this.yearrelase;
    }
    
    public void setYearrelase(int yearrelase) {
        this.yearrelase = yearrelase;
    }
    public String getAuthorname() {
        return this.authorname;
    }
    
    public void setAuthorname(String authorname) {
        this.authorname = authorname;
    }
    public String getTimestimp() {
        return this.timestimp;
    }
    
    public void setTimestimp(String timestimp) {
        this.timestimp = timestimp;
    }
    public String getImageurl() {
        return this.imageurl;
    }
    
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }
    public Set getUserbooks() {
        return this.userbooks;
    }
    
    public void setUserbooks(Set userbooks) {
        this.userbooks = userbooks;
    }




}


