package pojo;
// Generated May 21, 2016 2:00:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Userbook generated by hbm2java
 */
public class Userbook  implements java.io.Serializable {


     private Integer id;
     private Appuser appuser;
     private Books books;
     private String available;
     private boolean ownership;
     private boolean wish;
     private int rating;
     private Set userborrowbooks = new HashSet(0);

    public Userbook() {
    }

	
    public Userbook(Appuser appuser, Books books, String available, boolean ownership, boolean wish, int rating) {
        this.appuser = appuser;
        this.books = books;
        this.available = available;
        this.ownership = ownership;
        this.wish = wish;
        this.rating = rating;
    }
    public Userbook(Appuser appuser, Books books, String available, boolean ownership, boolean wish, int rating, Set userborrowbooks) {
       this.appuser = appuser;
       this.books = books;
       this.available = available;
       this.ownership = ownership;
       this.wish = wish;
       this.rating = rating;
       this.userborrowbooks = userborrowbooks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Appuser getAppuser() {
        return this.appuser;
    }
    
    public void setAppuser(Appuser appuser) {
        this.appuser = appuser;
    }
    public Books getBooks() {
        return this.books;
    }
    
    public void setBooks(Books books) {
        this.books = books;
    }
    public String getAvailable() {
        return this.available;
    }
    
    public void setAvailable(String available) {
        this.available = available;
    }
    public boolean isOwnership() {
        return this.ownership;
    }
    
    public void setOwnership(boolean ownership) {
        this.ownership = ownership;
    }
    public boolean isWish() {
        return this.wish;
    }
    
    public void setWish(boolean wish) {
        this.wish = wish;
    }
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }
    public Set getUserborrowbooks() {
        return this.userborrowbooks;
    }
    
    public void setUserborrowbooks(Set userborrowbooks) {
        this.userborrowbooks = userborrowbooks;
    }




}


